version: '3.1'
services:
  mysql-service:
    container_name: docker-mysql
    image: 'mysql:5.7'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: "prontuario"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: 123
    ports:
      - 3306:3306
      
  spring:
    build:
      context: .
    container_name: docker-spring
    volumes:
      - .:/app
    restart: always
    ports:
      - 7070:7070
    depends_on:
      - mysql-service