version: "3.1"
services:
    mysql-service:
        restart: always
        container_name: e-prontuario_mysql
        image: "mysql:5.7"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: "prontuario"
            MYSQL_USER: "app"
            MYSQL_PASSWORD: 123
        ports:
            - 3306:3306

    spring:
        restart: always
        build:
            context: backend/e-prontuario
        container_name: e-prontuario_spring
        ports:
            - 7070:7070
        volumes:
            - /tmp
        depends_on:
            - mysql-service

    web:
        restart: always
        image: e-prontuario_web:${NG_ENV}
        build:
            context: frontend/e-prontuario/
            args:
                env: ${NG_ENV}
                base_href: ${NG_BASE_HREF}
        container_name: "e-prontuario_web_1"
        ports:
            - "3000:70"
        volumes:
            - /app/node_modules
            - .:/app
